# Generated by Django 3.0.3 on 2020-02-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
